name: vaultblocks_mobile
description: Vaultblocks mobile app and monorepo root.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  internals:
    path: internals

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.2

flutter:
  uses-material-design: true
