name: vaultblocks_mobile
description: Vaultblocks mobile app and monorepo root.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  core:
    path: internals/core
  account_management:
    path: internals/account_management

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.2

flutter:
  uses-material-design: true
